<?php

namespace SFW\Config;

/**
 * System config (not available from templates).
 */
class Sys extends \SFW\Config
{
    /**
     * Returns array with config parameters.
     */
    public function get(): array
    {
        return [
            // {{{ frontend

            /* Basic url of site (autodetect if not set).
             *
             * ?string
             */
            'basic_url' => null,

            /* Add statistics to each page generated by template.
             *
             * bool
             */
            'add_stats_to_page' => true,

            /* Name of page param in url for paginator.
             *
             * string
             */
            'param_for_paginator' => 'i',

            // }}}
            // {{{ database

            /* Default database driver Mysql or Pgsql (can be changed at runtime).
             *
             * string
             */
            'db' => 'Mysql',

            /* How many times to retry failed transactions with expected sql states.
             *
             * int
             */
            'db_transactions_retries' => 7,

            /* Log transactions fails.
             *
             * ?string
             */
            'db_transactions_fails_log' => APP_DIR . '/var/log/transactions.fails.log',

            /* Log slow queries.
             *
             * ?string
             */
            'db_slow_queries_log' => APP_DIR . '/var/log/slow.queries.log',

            /* Log slow queries with minimal time in seconds.
             *
             * float
             */
            'db_slow_queries_min' => 0.5,

            // }}}
            // {{{ database: postgresql

            /*
             * Postresql connection string.
             *
             * string
             */
            'db_pgsql_connection' => '',

            /* Postgresql encoding (utf-8 if not set).
             *
             * ?string
             */
            'db_pgsql_encoding' => null,

            /* Postgresql persistent connection (use pgbouncer instead).
             *
             * bool
             */
            'db_pgsql_persistent' => false,

            // }}}
            // {{{ database: mysql

            /* Mysql hostname.
             *
             * ?string
             */
            'db_mysql_hostname' => null,

            /* Mysql username.
             *
             * ?string
             */
            'db_mysql_username' => null,

            /* Mysql password.
             *
             * ?string
             */
            'db_mysql_password' => null,

            /* Mysql database name.
             *
             * ?string
             */
            'db_mysql_database' => null,

            /* Mysql port (3306 if not set).
             *
             * ?int
             */
            'db_mysql_port' => null,

            /* Mysql socket.
             *
             * ?string
             */
            'db_mysql_socket' => null,

            /* Mysql charset (utf8mb4 if not set).
             *
             * ?string
             */
            'db_mysql_charset' => null,

            // }}}
            // {{{ cache

            /* Default cache Apc or Memcached (can be changed at runtime).
             *
             * string
             */
            'cache' => 'Apc',

            // }}}
            // {{{ cache: apc

            /* Apc default TTL.
             *
             * int
             */
            'cache_apc_ttl' => 3600,

            /* Apc namespace (auto if not set).
             *
             * ?string
             */
            'cache_apc_ns' => null,

            // }}}
            // {{{ cache: memcached

            /* Memcached default TTl.
             *
             * int
             */
            'cache_memcached_ttl' => 3600,

            /* Memcached namespace (auto if not set).
             *
             * ?string
             */
            'cache_memcached_ns' => null,

            /* Memcached options.
             *
             * ?array(KEY => VALUE, ...)
             */
            'cache_memcached_options' => null,

            /* Memcached servers (127.0.0.1:11211 if not set).
             *
             * ?array(array('HOST', PORT), ...)
             */
            'cache_memcached_servers' => null,

            // }}}
            // {{{ mail

            /* Enable mailer.
             *
             * If disabled, then no emails will be sent, but build() method in Notify classes will be called anyway.
             *
             * bool
             */
            'mailer' => true,

            /* Instead of disabling, you can override recipients by your email.
             *
             * array('EMAIL' or array('EMAIL'[, 'NAME']), ...)
             */
            'mailer_override_recipients' => [],

            // }}}
            // {{{ etc

            /* Lock files pattern.
             *
             * string
             */
            'lock_files_pattern' => APP_DIR . '/var/locks/%s.lock',

            /* Default timezone.
             *
             * string
             */
            'timezone' => 'Europe/Moscow',

            // }}}
        ];
    }
}
